name: humanSayMonkeyDo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - notebook
  - numpy
  - scipy
  - matplotlib
  - pandoc
  - pandas
  - ipywidgets
  - scikit-learn
  -pynwb
  - pip
  - pip:
    - dandi